import { TrainingCourse, CaseStudy, GalleryItem, ServicePillar, LegalityBlock } from './types';

export const ASSETS = {
  logo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB55aVJJvnQbuZzdo4p5rjExVZJ62NxBKL27hzPq1fXNgqhR_9qLz7btB0Eb415bOLh1eEIMKRScKPd3DHATtFZUqDTjFMqPrZ2u70eQI0r6hhDT_941oqF6SbuVtFC8NrcF9nHgXRG2WeDIOM6y4cSXMI3q_uG5qxTyGHExt3dN5ZxVyVudoRGfDpvgxMZnvSjdkJZ7WADKs2jSH3W20RT2mOgKEuwUTySs9fpGhI9fH5wNzny-p3TIjz6sx5STpexjGc',
  footerLogo: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCZGx3CeBhWr5DA9FIPyaOuVsRywuVNxMeYmMkTR-MqRtPXb8XW0dKYoE9yQAvaK0OopBvj-dAYLQpBGiT5A56nbtMHJit8Yj--nQx-WCAOC8Zeg1e5VAUamyMZMHZW3CAxDNEOLjlcwoknDTRmUOp3hPakzGQ3rIdc-qOQDCxh1C5z-mb8KSkxUptKrq0xQb7g1bQEs3A6Ek3TVUXHQU4fqJGDZkaAAdYFWBN_6q8MDixo05UElm0g8KbqDPnHMU6BWLM',
  founder: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDd2raQCi2r8ZbJTp9IVqA3UpK0a7EbErf0HZCbXywbHD5QxKO7LHUYQSMUZvlOkS7GZvlpf6ULMLsCewo9JYhXx5RdOF99WtiDn199c6ay2oMzSBeYjDBPMro_mopKEJju_9hLezGrsCIQvtl8-v4tuFyrEl4nQHdrfldFpP0kpcHbiNa6SV065ll-iiwyml3bIl_KfJ5GzebLYoDImaDX_RVQkxxZvjGzZxwhqU2QHp6hEth62W_8pwTEE1-IFckMDs8',
  citaMineral: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA8j-SRpL3Idx6POeO4izTFulmeb5xDbWRhPnUoANiwdSKTyyDNtFN0pAxWtqBmumlNF2JwHmQtAEh_hQ8WH8jz599cIrMZdFuQupYHqVB-BDnK0bu0I5YkOeZHv08YNsx2BGJ2-PwuhPUeL3oYDBavYlJeC7y8gF8a03sIsu_n6ZQTOX_aCGjhs_sI3z-_71_TIkiVTEXQhMIjnIwEv8ZkccJrekEE1H0zlHSwAGmY9F2BP89R2nf7XVmyIJO96TwAemg',
  rsudHadrianus: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-5e4f8M_CoBBtxX14_B6HrC-wJI93cA55_tO4fui9rPZ3q8CfZA7uMN8ynINIPOZ0X7w_QZhmudoGLlz5fHtHgmcK-6oSI3xolkdFrHaAUB1n6S7PUCn2Y3Xny4iwlAQSTNPSuJtvEPOIQZtjqhErR06D1V8GDUkextDX4RpKnbnPPDqJRCh09U2VF_panqyk6Ha-0RiRL39F039p0Eixf6Lw6f91CaTZy36iSua3Pp6poP1OR7VJTQSMlKxVZ46Q8JU',
  imdgPort: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlm8g5ig9eTxeez6a6PMpy5J7owng7R5EEme58nCjltXKPJnDrjZCJ03-8auBJE85hZ3zWwjg-aVdg2N_0z0yZrpK9hkCSM-ndgCXKG4WDEKLVPuNqz_KTF3aZw_CpIetfKvbmcI3LFJH7sAQy6DewYMQhR-a6-vkR_RoNgI5A7ernPWxp7pu7hsJtCgjkXLlod0B9jEkJzZjLDl1zqV9osk7L5At_fDaT8ZJyLXu-l8TvZAHOTI5GTY_63CXRrNapgBs',
  plnItb: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAAQ1LgfJMYBn3nwDjGuYUNkNGyoSDpAMduUja2b4Kw0Yrn_KT6A5a8icm1d6ql_V5-rnzV1s4PDJIOg2PzeoHu0JCFYQHWsecM1xWTamLyTtFv4kf-u1Osk8wbynuBAHIwlIFn0KBzva02A0cQglIFSBtH1vv0llTRsEUtBTrMSuXodcuCwfeDi9vm9W347wGaKOe1H9Mz0lV-UPVn1zBW9OdkgQpMxJYSY0e5DKxqcx8UJBniKBp7DMVZXBuVQbgPQJk',
  fieldHybrid: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC-azXXpw49oM6LACERBeXPdbvfsssKlwgDUHPhK-wSLQx0cRn8_gdLmgxLQ5Y4LVI_yvH0_9l0CBoP-OtIjmgf4KZDPkguSssC3fqLWZ2sWOvcTMArZn2ueL1dBdHtaGtEdX5mp3JuxbWSv3_k_RyxAzacqqbA-jA2UjPbu5K30O4PFTncR13019aGImbku5zlBUzPE-Qvh7cKUhlnBK-qMbNYdEooeqzQlIFvqZ40NpTaUzGmndPEdRBOP3tDQx4Z2Cg',
  ksopAward: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDECuB1eYZHeDUBTFhzRmc-yPaNjbQAZm6HSh40T9AQLoMqTHvAL72aA1e7zmSaLC8XtHaeNAlMdv3Pc0S4hcAoRbxNppqKZ0wQIPwffeNyoivsuUzqANsKz1mPAAkpuR5z1dPHTBOvkyYs1GPu_4yR0v6bOGzkmDokHaU08nZostTwubWQBQKoPSKlniFnZQEVNROstZ7U4MtJP4Mrd7AuVJfEypKCj5fXrFjrlK2ZNBkiWeqINRNbRKfdN-Y4_UaEVLQ',
  lspMandiri: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAQ1URqEFGXEa7OvN4ovO5RGlGjb_v8oInP6CW5jGqNXz8Y6d7sJu0LyFoZVRayrHtnPA4vHMPXT9KO6JcwVfzPCQi7QBpMeFoECNbNztCxHatXA0bBDroBF04ng3z2H7aWwVbbG37RVyZY6JhVL6j8rNhtfq8gzNNruxWTUWOidxKkzwHLc9DXYX6MQ8Yxh_nshVF8wsafyP5j8WE6wdbVO8s8u1OrPDE7KflyWjG2NlIP8QMprCY1_Hv-MZI8CjU8RLU',
  portInspection: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBjBz-i_bcyg4bgIEHiqTDxFgGPeRhQIIrCJzxjvSVWVGlrIKx7LB8QPh6rGAitfoaWmKpGAVIAULoYSKHouqv_aQ_E3H4ljanti3SoiqOxOTOY4MkPyBvA-CqsNBn2GKwNG9Jk6z6JHfs-TmHgmvNNfb-ukUoHV-pfnaWsntb6Bw-ICmcKB2KTwiB6jQldgIoGTtNtXAP7Y_RCUi2oKnNF97YsfvEGurDiMlsNZVDjwDhc948Se6mOeQn6jrWJFeYfw0w',
  classroomWorkshop: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDILvyIg2N6-Uy1s3SWZ6uUVoskXrKjZXaPvv3JvlQc8_doMRec7zUqQvFDw5msNCeksLKdSigil_yPsMSEz7psf2SEJwHyR7GOn4bwFPwMzpGe7TkC09J2tGXWBRgZChO2a24vdx0-w2yf-5DlTWbROezJvwAgvkQFXra9Xrjj--p4HOvyjnW7-O4nQwwXHOAevtHTWkJHuDF_1p7mF6PkfVQu58Oi6SpbIG7khZzNgRHB1vchfUVYP4r57TW_l81p5RQ',
  officeBuilding: '/assets/office_building.jpg',
};

export const COMPANY_INFO = {
  name: 'PT JAYA PASIFIC SOLUTION',
  tagline: 'Professional Training & Integrated Management System',
  phone1: '0811-1595-122',
  phone2: '0812-8829-5950',
  email: 'jayapasificsolution90@gmail.com',
  secondaryEmail: 'info@jayapasificsolution.com',
  address: 'Jl. Hutama Karya No.12A, Kademangan, Kec. Setu, Kota Tangerang Selatan, Banten 15314',
  plusCode: 'MM58+2W Kademangan, Kota Tangerang Selatan, Banten',
  coordinates: { lat: -6.342477, lng: 106.6673181 },
  mapsUrl: 'https://www.google.com/maps/place/Jaya+Pasific+Solution/@-6.3425974,106.6673205,17z/data=!4m15!1m8!3m7!1s0x2e69e548485c172f:0xe59f7f75754e1444!2sJaya+Pasific+Solution!8m2!3d-6.342477!4d106.6673181!10e5!16s%2Fg%2F11p5hd3p_4!3m5!1s0x2e69e548485c172f:0xe59f7f75754e1444!8m2!3d-6.342477!4d106.6673181!16s%2Fg%2F11p5hd3p_4',
  openingHours: 'Senin - Jumat: 09.00 - 17.00 WIB',
  skpNumber: 'No. Reg. K3/PJK3/BINWASK3-PNK3/2024',
  nibNumber: 'NIB 0220202930412 (KBLI 78429, 70209)',
  npwp: '61.782.910.4-411.000 (PKP Terdaftar)',
};

export const COURSES: TrainingCourse[] = [
  {
    id: 'ak3u-kemnaker-palembang',
    code: 'KEMNAKER-AK3U-2026',
    title: 'Pembinaan & Sertifikasi Calon Ahli K3 Umum (AK3U)',
    category: 'kemnaker',
    badge: 'KEMNAKER RI CERTIFICATION',
    badgeColor: 'bg-[#0B8F36]',
    duration: '13 Hari + 1 Hari Ujian Kemnaker',
    description: 'Program wajib kepatuhan UU No. 1 Tahun 1970 dan Permenaker No. 02/MEN/1992. Mempersiapkan sekretaris P2K3 profesional dengan kewenangan hukum mengawasi keselamatan kerja di lingkungan industri.',
    location: "Parkside's Hotel Palembang (Ilir Timur I, Sumatera Selatan)",
    dates: '24 Agustus – 08 September 2026',
    instructor: 'Trainer Ahli Kemnaker RI & Pengawas Ketenagakerjaan Wilayah',
    personalPrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    corporatePrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    featured: true,
    facilities: [
      'Sertifikat Calon Ahli K3 Umum Resmi Kemnaker RI',
      'Surat Keputusan Penunjukan (SKP) & Lisensi Kewenangan Kemnaker',
      'Hardcopy Buku Himpunan Peraturan Perundangan K3 (Lengkap)',
      'Pin Keselamatan Kerja & Safety Polo Shirt Eksklusif JPS',
      'Ransel Kerja / Backpack & Vacuum Tumbler Stainless',
      'Lunch Buffet & 2x Coffee Break Harian (14 Hari Penuh)',
      'Praktek Kerja Lapangan (PKL) Observasi K3 Industri Nyata',
      'Modul Pelatihan, Seminar Kit & Training Pad',
    ],
    syllabus: [
      'Kebijakan Nasional K3 & UU No. 1 Tahun 1970',
      'Dasar-dasar K3 & Pengawasan Kelembagaan K3 (P2K3)',
      'K3 Bidang Mesin, Pesawat Uap & Bejana Tekan',
      'K3 Bidang Mekanik, Instalasi Listrik & Penanggulangan Kebakaran',
      'K3 Bidang Konstruksi Bangunan & Kesehatan Kerja',
      'K3 Lingkungan Kerja & Bahan Berbahaya Beracun (B3)',
      'Sistem Manajemen K3 (SMK3 PP 50/2012) & Audit Internal',
      'Praktek Kerja Lapangan (PKL) Industri & Penyusunan Laporan',
      'Seminar Evaluasi Laporan PKL & Ujian Komprehensif Kemnaker RI',
    ],
    requirements: [
      'Pendidikan Minimal D3 / S1 (Semua Jurusan Teknik / Non-Teknik)',
      'Fotokopi Ijazah Terakhir Legalisi & Transkrip Nilai (2 Lembar)',
      'Fotokopi KTP / Identitas Diri (2 Lembar)',
      'Pas Foto Berlatar Merah (2x3, 3x4, 4x6 masing-masing 4 Lembar)',
      'Surat Rekomendasi Perusahaan (khusus pendaftaran Korporat / Utusan)',
    ],
  },
  {
    id: 'tot-level-6-master',
    code: 'BNSP-TOT-LV6',
    title: 'Training of Trainer (TOT) Master Trainer Level 6 - Sertifikasi BNSP',
    category: 'bnsp',
    badge: 'BNSP SKKNI LEVEL 6',
    badgeColor: 'bg-[#102A43]',
    duration: '3 Hari + Ujikom',
    description: 'Sertifikasi tertinggi bagi instruktur senior, konsultan korporat, dan head of learning development untuk mendesain kurikulum, strategi instruksional, serta standarisasi pelatihan berstandar BNSP.',
    location: 'Gedung Yustinus Lt. 14, Universitas Katolik Indonesia Atma Jaya, Jl. Jend. Sudirman No. 51, Jakarta Selatan',
    dates: '16 – 19 Oktober 2026',
    instructor: 'Johannes Simanjuntak, SKM, M.Kes (Master Trainer & Assessor BNSP)',
    personalPrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    corporatePrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    facilities: [
      'Sertifikat Kompetensi Instruktur Utama / Master Trainer BNSP (Garuda)',
      'Modul SKKNI Pelatihan Kerja Skema Level 6',
      'Bimbingan Penyusunan Portofolio Unit Kompetensi Lengkap',
      'Konsumsi Lunch & Coffee Break di Venue Atma Jaya',
      'Sertifikat Kehadiran Training Provider PT Jaya Pasific Solution',
      'Jaringan Profesional Master Trainer Nasional',
    ],
    syllabus: [
      'Merancang Program Pelatihan Kerja Berbasis Kompetensi (CBT)',
      'Menyusun Kurikulum & Silabus Pelatihan Berbasis Unit Kompetensi',
      'Mengembangkan Perangkat Pembelajaran & Media Interaktif',
      'Mengelola Penyelenggaraan Pelatihan Korporat Terstruktur',
      'Melakukan Evaluasi Tingkat Efektivitas Pelatihan (Kirkpatrick Level 1-4)',
      'Simulasi Micro-Teaching Terpandu & Pra-Asesmen Uji Kompetensi',
    ],
    requirements: [
      'Pengalaman Mengajar / Melatih minimal 3 tahun atau lulusan ToT Level 4',
      'Ijazah minimal S1/D4',
      'Portofolio bukti kerja mengajar & silabus yang pernah dibuat',
    ],
  },
  {
    id: 'tot-level-4-instruktur',
    code: 'BNSP-TOT-LV4',
    title: 'Training of Trainer (TOT) Instruktur Level 4 - Sertifikasi BNSP',
    category: 'bnsp',
    badge: 'BNSP SKKNI LEVEL 4',
    badgeColor: 'bg-[#102A43]',
    duration: '3 Hari + Ujikom',
    description: 'Standardisasi kompetensi mengajar untuk internal trainer perusahaan, supervisor K3, dan praktisi industri dalam membawakan materi dengan metode pedagogik & andragogik yang efektif.',
    location: 'Hotel Santika Premiere / In-House Client Company',
    dates: '12 – 14 November 2026',
    instructor: 'Tim Asesor Resmi LSP Pelatihan Terakreditasi',
    personalPrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    corporatePrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    facilities: [
      'Sertifikat Kompetensi Instruktur Metodologi BNSP',
      'Formulir & Template Portofolio Asesmen',
      'Simulasi Praktek Mengajar (Microteaching) dengan Feedback Ahli',
      'Sertifikat Pelatihan Resmi JPS',
      'Coffee Break & Lunch',
    ],
    syllabus: [
      'Menerapkan Prinsip Keselamatan dan Kesehatan Kerja di Tempat Kerja',
      'Menentukan Kebutuhan Pelatihan Individu & Kelompok',
      'Menyusun Rencana Sesi Pelatihan (Lesson Plan)',
      'Memfasilitasi Pembelajaran Partisipatif Dewasa (Andragogi)',
      'Menggunakan Media & Sumber Belajar Interaktif',
      'Pelaksanaan Uji Kompetensi oleh Asesor LSP BNSP',
    ],
    requirements: [
      'Pendidikan Minimal D3 semua jurusan',
      'CV & Surat Rekomendasi/Keterangan Pernah Mengajar/Presentasi',
    ],
  },
  {
    id: 'pop-minerba-esdm',
    code: 'ESDM-POP-2026',
    title: 'Pengawas Operasional Pertama (POP) Pertambangan - Sertifikat BNSP',
    category: 'minerba',
    badge: 'BNSP & KEMENTERIAN ESDM',
    badgeColor: 'bg-[#B45309]',
    duration: '3 Hari + Ujikom',
    description: 'Sertifikasi kompetensi pengawas garda terdepan industri pertambangan minerba sesuai Kepmen ESDM No. 1827 K/30/MEM/2018 tentang Pedoman Pelaksanaan Kaidah Teknik Pertambangan yang Baik.',
    location: 'Balikpapan / Pontianak / In-House Site Tambang',
    dates: 'Batch Aktif Setiap Bulan (On Request Corporate)',
    instructor: 'Senior Mining Inspector & Asesor LSP Pertambangan',
    personalPrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    corporatePrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    facilities: [
      'Sertifikat Kompetensi Kerja Pengawas Operasional Pertama (POP) BNSP',
      'Buku Panduan Uji Kompetensi POP Minerba',
      'Pendampingan Pemenuhan Portofolio Logbook Kerja Lapangan',
      'Simulasi Tanya Jawab Lisan & Studi Kasus Lapangan',
      'Konsumsi & Training Kit Lengkap',
    ],
    syllabus: [
      'Dasar-dasar Hukum K3 Pertambangan Minerba (Kepmen 1827)',
      'Tugas dan Tanggung Jawab Pengawas Operasional Pertama (POP)',
      'Pemeriksaan dan Inspeksi K3 Tempat Kerja',
      'Penyelidikan / Investigasi Kecelakaan Tambang & Analisis Penyebab',
      'Analisis Keselamatan Kerja (JSA) & HIRADC Tambang',
      'Pertemuan K3 Terencana (Safety Talk / Toolbox Meeting)',
      'Pelaksanaan Asesmen Mandiri & Uji Wawancara Asesor LSP',
    ],
    requirements: [
      'Minimal D3 Pengalaman 1 tahun di pertambangan atau SMA/SMK Pengalaman 3 tahun',
      'Surat Keterangan Pengalaman Kerja dari KTT / HRD Perusahaan Tambang',
    ],
  },
  {
    id: 'k3rs-healthcare',
    code: 'KEMKES-K3RS-2026',
    title: 'Pelatihan & Pendampingan K3 Rumah Sakit (K3RS)',
    category: 'k3rs',
    badge: 'KEMKES RI & STANDAR AKREDITASI',
    badgeColor: 'bg-[#0B8F36]',
    duration: '3 Hari Pelatihan Teknis & Audit Mockup',
    description: 'Kepatuhan Permenkes No. 66 Tahun 2016 tentang K3RS. Dirancang khusus untuk komite K3 RSUD, RS Swasta, dan klinik rawat inap guna pemenuhan akreditasi STARKES dan KARS.',
    location: 'In-House Rumah Sakit / Hybrid Seluruh Indonesia',
    dates: 'Jadwal Fleksibel Corporate / Rumah Sakit',
    instructor: 'Konsultan Senior Manajemen K3RS & Asesor Akreditasi',
    personalPrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    corporatePrice: 'Konsultasikan Program & Dapatkan Penawaran Terbaik',
    facilities: [
      'Sertifikat Resmi K3 Rumah Sakit PT Jaya Pasific Solution',
      'Template SOP & Pedoman K3RS Terintegrasi Siap Pakai',
      'Audit Lapangan & Walkthrough Fasilitas Medis / Non-Medis',
      'Tools Penilaian Risiko B3 Medis & Disaster Plan Rumah Sakit',
    ],
    syllabus: [
      'Regulasi Permenkes 66/2016 & Standar MFK Akreditasi RS',
      'Keselamatan dan Keamanan Fasilitas Fisik Rumah Sakit',
      'Pengelolaan Bahan Berbahaya dan Beracun (B3) Medis & Limbah B3',
      'Kesiapsiagaan Tanggap Darurat Bencana (Hospital Disaster Plan)',
      'Sistem Proteksi Kebakaran & Simulasi Code Red di Ruang Perawatan',
      'Kesehatan Kerja bagi Tenaga Medis, Nakes & Penunjang',
    ],
    requirements: [
      'Anggota Komite K3RS, Manajer Operasional, Sanitasi, atau Tim PPI Rumah Sakit',
    ],
  },
];

export const SERVICE_PILLARS: ServicePillar[] = [
  {
    id: 'training',
    icon: 'GraduationCap',
    title: 'Professional Training',
    subtitle: 'Peningkatan Kompetensi Tenaga Kerja',
    description: 'Program pembinaan sertifikasi berlisensi resmi pemerintah untuk memastikan seluruh personel memiliki legalitas dan kecakapan teknis.',
    bulletPoints: [
      'Ahli K3 Umum (AK3U) Sertifikasi Kemnaker RI',
      'Pengawas Operasional Tambang (POP / POM Minerba ESDM)',
      'K3 Rumah Sakit (K3RS) & Fasilitas Pelayanan Kesehatan',
      'Training of Trainer (ToT) Instruktur BNSP Level 4 & 6',
      'Petugas Peran Kebakaran, First Aid (P3K) & Ruang Terbatas (Confined Space)',
    ],
    actionLabel: 'Lihat Jadwal Pelatihan',
    actionHref: '#training-marketplace',
  },
  {
    id: 'certification',
    icon: 'Award',
    title: 'Certification Program',
    subtitle: 'Standarisasi Resmi Kemnaker & BNSP',
    description: 'Penyelenggaraan uji kompetensi resmi berbasis Standar Kompetensi Kerja Nasional Indonesia (SKKNI) dan regulasi ketenagakerjaan.',
    bulletPoints: [
      'Sertifikasi Personel Lisensi Kemnaker RI & SKP Penunjukan',
      'Uji Kompetensi Lembaga Sertifikasi Profesi (LSP) BNSP RI',
      'Sertifikasi Personel Penanganan Muatan Berbahaya (IMDG Code)',
      'Auditor Internal & Lead Auditor SMK3 PP 50 / ISO',
      'Verifikasi Portofolio Kerja & Penerbitan Sertifikat Garuda',
    ],
    actionLabel: 'Konsultasi Sertifikasi',
    actionHref: '#corporate-solution',
  },
  {
    id: 'consulting',
    icon: 'ShieldCheck',
    title: 'Management Consulting',
    subtitle: 'Implementasi & Pendampingan Sistem',
    description: 'Konsultansi terintegrasi mendampingi perusahaan dari gap analysis, pemetaan proses bisnis, hingga lolos audit sertifikasi internasional.',
    bulletPoints: [
      'ISO 9001:2015 (Sistem Manajemen Mutu)',
      'ISO 14001:2015 (Sistem Manajemen Lingkungan)',
      'ISO 45001:2018 (Sistem Manajemen K3 Internasional)',
      'SMK3 PP 50/2012 (Bendera Emas / Sertifikat Kemnaker)',
      'Contractor Safety Management System (CSMS) & Dokumen Pra-Kualifikasi',
      'Risk Assessment & HIRADC Industrial Master Plan',
    ],
    actionLabel: 'Konsultasi ISO & SMK3',
    actionHref: '#corporate-solution',
  },
  {
    id: 'inhouse',
    icon: 'Building2',
    title: 'Corporate In-House Solution',
    subtitle: 'Solusi Tailor-Made di Lokasi Perusahaan',
    description: 'Pelatihan dan audit langsung di fasilitas kerja Anda dengan kurikulum yang disesuaikan secara presisi terhadap risiko operasional pabrik atau tambang.',
    bulletPoints: [
      'Simulasi Tanggap Darurat (ERP & Code Red Drill)',
      'Walk-Through Hazard Inspection & Risk Profiling',
      'Bilingual Training untuk Perusahaan Multinasional / PMA',
      'Audit Kesiapan Sertifikasi Mandiri (Mock-Up Audit)',
      'Laporan Evaluasi Pasca Pelatihan untuk Manajemen Eksekutif',
    ],
    actionLabel: 'Request In-House Proposal',
    actionHref: '#corporate-solution',
  },
];

export const CASE_STUDIES: CaseStudy[] = [
  {
    id: 'cita-mineral',
    company: 'PT Cita Mineral Investindo Tbk',
    title: 'Mining Safety Basic & Heavy Equipment Hazard Workshop',
    category: 'Pertambangan',
    categoryLabel: 'Mining & Mineral Extraction',
    description: 'Pelatihan intensif penanganan keselamatan kerja operasi tambang bauksit, kepatuhan kaidah teknik pertambangan Kepmen ESDM 1827, serta penegakan budaya nihil kecelakaan (Zero Accident).',
    imageUrl: ASSETS.citaMineral,
    tag: 'MINING SAFETY',
    highlightMetric: '100% Peserta Lulus Uji Kompetensi',
  },
  {
    id: 'rsud-hadrianus',
    company: 'RSUD dr. Hadrianus Sinaga',
    title: 'Hospital Occupational Safety & Accreditation (K3RS)',
    category: 'Kesehatan',
    categoryLabel: 'Healthcare & Public Hospital',
    description: 'Pendampingan implementasi keselamatan kerja komprehensif bagi seluruh jajaran dokter, perawat, instalasi gizi, dan penunjang medis sesuai Permenkes 66/2016 guna mendukung akreditasi paripurna.',
    imageUrl: ASSETS.rsudHadrianus,
    tag: 'HEALTHCARE SAFETY',
    highlightMetric: 'Standar MFK Paripurna Kemenkes',
  },
  {
    id: 'imdg-port',
    company: 'Port Operations & Terminal Petikemas',
    title: 'IMDG Code Dangerous Goods Handling & Harbor Safety',
    category: 'Maritim',
    categoryLabel: 'Port Authority & Logistics Terminal',
    description: 'Standardisasi internasional penanganan muatan bahan kimia berbahaya dan beracun (B3) di dermaga pelabuhan logistik Makassar sesuai regulasi International Maritime Organization (IMO).',
    imageUrl: ASSETS.imdgPort,
    tag: 'MARITIME & PORT SAFETY',
    highlightMetric: 'Zero Spill & Full IMO Compliance',
  },
  {
    id: 'pln-itb',
    company: 'PT PLN (Persero) & LAPI ITB',
    title: 'Executive Risk Management & Power Plant Safety',
    category: 'Energi',
    categoryLabel: 'National Power Utility & Academic Consortium',
    description: 'Kolaborasi strategis pengembangan kapasitas manajerial dan kepemimpinan K3 tingkat lanjut untuk pemeliharaan infrastruktur ketenagalistrikan nasional bertegangan tinggi.',
    imageUrl: ASSETS.plnItb,
    tag: 'ENERGY & POWER GRID',
    highlightMetric: 'Strategic Safety Leadership',
  },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: 'ksop-award',
    title: 'Plakat Penghargaan Narasumber Ahli HIRADC & Incident Investigation',
    organization: 'Kantor Kesyahbandaran dan Otoritas Pelabuhan (KSOP) Kelas I Panjang',
    badge: 'NARASUMBER AHLI NASIONAL',
    location: 'Bandar Lampung, Sumatera Selatan',
    imageUrl: ASSETS.ksopAward,
    description: 'Apresiasi resmi dari Kepala Kantor KSOP Kelas I Panjang kepada Bapak Johannes Simanjuntak, SKM, M.Kes atas kontribusi kepakaran dalam evaluasi identifikasi bahaya dan investigasi insiden maritim.',
    tag: 'PENGHARGAAN RESMI',
    statusBadge: 'Verified Keynote Speaker',
  },
  {
    id: 'lsp-mandiri-mining',
    title: 'Pelatihan Peningkatan Kompetensi & Sertifikasi Asesor Pertambangan',
    organization: 'LSP Pertambangan Indonesia Mandiri - Badan Nasional Sertifikasi Profesi (BNSP)',
    badge: 'ASESOR BNSP & ESDM',
    location: 'Hotel Horison Ultima',
    imageUrl: ASSETS.lspMandiri,
    description: 'Sinergi berkala para Asesor Kompetensi Nasional bersama Ditjen Minerba Kementerian ESDM guna standardisasi rubrik pengujian sertifikasi POP, POM, dan POU.',
    tag: 'KOMPETENSI ASESOR',
    statusBadge: 'Official Assessor Forum',
  },
  {
    id: 'port-inspection-drill',
    title: 'Inspeksi Bahaya Lapangan & Walk-Through Dermaga Logistik',
    organization: 'Otoritas Pelabuhan & Operator Bongkar Muat B3',
    badge: 'SITE INSPECTION & AUDIT',
    location: 'Fasilitas Dermaga Internasional',
    imageUrl: ASSETS.portInspection,
    description: 'Pemeriksaan lapangan terpadu bersama tim safety pelabuhan mengevaluasi crane spreader, containment bunding bahan kimia, dan jalur evakuasi dermaga.',
    tag: 'OBSERVASI LAPANGAN',
    statusBadge: 'Field Walk-Through',
  },
  {
    id: 'classroom-workshop',
    title: 'Workshop Penyusunan Dokumen HIRADC & Bedah Matriks Risiko',
    organization: 'Corporate In-House Team & Departemen QHSE',
    badge: 'INTERACTIVE WORKSHOP',
    location: 'Ruang Pelatihan Korporat',
    imageUrl: ASSETS.classroomWorkshop,
    description: 'Sesi praktikum interaktif bedah kasus kecelakaan kerja aktual, penentuan tingkat konsekuensi dan kemungkinan, serta penetapan hierarki kontrol bahaya.',
    tag: 'METODOLOGI KASUS',
    statusBadge: 'Hands-on Risk Matrix',
  },
];

export const LEGALITY_BLOCKS: LegalityBlock[] = [
  {
    id: 'kemnaker',
    authority: 'Kementerian Ketenagakerjaan RI',
    title: 'PJK3 Resmi Terdaftar (Binwas K3)',
    description: 'Memiliki Surat Keputusan Penunjukan (SKP) resmi sebagai Perusahaan Jasa Keselamatan dan Kesehatan Kerja untuk pembinaan teknis dan sertifikasi personel.',
    iconName: 'Building2',
    badge: 'SKP REG. K3/PJK3/2024',
  },
  {
    id: 'bnsp',
    authority: 'Badan Nasional Sertifikasi Profesi (BNSP)',
    title: 'Tempat Uji Kompetensi (TUK) Mandiri',
    description: 'Bekerja sama dengan LSP Terlisensi BNSP mengacu pada Standar Kompetensi Kerja Nasional Indonesia (SKKNI) dengan hak terbit sertifikat berlogo Garuda.',
    iconName: 'Award',
    badge: 'STANDAR SKKNI GARUDA',
  },
  {
    id: 'kemenkumham',
    authority: 'Kementerian Hukum & HAM RI',
    title: 'Pengesahan Badan Hukum Perseroan Terbatas',
    description: 'Akta Pendirian Notaris dan Surat Keputusan Menteri Hukum dan HAM Republik Indonesia atas nama PT Jaya Pasific Solution sebagai entitas hukum sah.',
    iconName: 'Scale',
    badge: 'LEGALITAS PERSEROAN',
  },
  {
    id: 'nib',
    authority: 'Lembaga OSS - BKPM RI',
    title: 'NIB Berbasis Risiko & KBLI Terverifikasi',
    description: 'Nomor Induk Berusaha (NIB: 0220202930412) untuk KBLI 78429 (Pelatihan Kerja Swasta) dan KBLI 70209 (Aktivitas Konsultasi Manajemen Lainnya).',
    iconName: 'FileCheck',
    badge: 'OSS RISK-BASED NIB',
  },
  {
    id: 'djp',
    authority: 'Direktorat Jenderal Pajak (DJP)',
    title: 'Pengusaha Kena Pajak (PKP) & NPWP Resmi',
    description: 'Status perpajakan tertib, menerbitkan e-Faktur Pajak Pertambahan Nilai (PPN 11%) resmi untuk seluruh transaksi pengadaan korporasi swasta dan BUMN.',
    iconName: 'FileText',
    badge: 'FAKTUR PAJAK TERSEDIA',
  },
  {
    id: 'iso-quality',
    authority: 'Quality Management Standards',
    title: 'Komitmen Mutu ISO 9001:2015',
    description: 'Seluruh kurikulum, evaluasi pengajar, dan kepatuhan administratif dioperasikan mengacu pada standar manajemen mutu internasional secara konsisten.',
    iconName: 'ShieldCheck',
    badge: 'PROSES TERSTANDAR',
  },
];

export const WORKFLOW_STEPS = [
  {
    step: '01',
    title: 'Company Inquiry & TNA',
    subtitle: 'Analisis Kebutuhan Pelatihan',
    description: 'Perusahaan menyampaikan profil risiko, kebutuhan sertifikasi wajib, atau regulasi yang harus dipenuhi (Kemnaker/BNSP/ESDM).',
  },
  {
    step: '02',
    title: 'Expert Consultation',
    subtitle: 'Diskusi Teknis Lead Assessor',
    description: 'Sesi konsultasi awal bersama Master Trainer & Assessor Johannes Simanjuntak & tim ahli untuk memetakan silabus spesifik dan target lulusan.',
  },
  {
    step: '03',
    title: 'Customized Proposal',
    subtitle: 'Proposal Teknis & Penawaran Investasi',
    description: 'Penyusunan penawaran formal mencakup jadwal rinci, materi, instruktur ahli, rincian fasilitas lengkap, serta termin pembayaran.',
  },
  {
    step: '04',
    title: 'Agreement & MoU',
    subtitle: 'Kontrak Kerja & Administrasi Resmi',
    description: 'Finalisasi nota kesepahaman (MoU), faktur pajak, dan surat penugasan resmi sebelum pelaksanaan program pelatihan atau audit.',
  },
  {
    step: '05',
    title: 'Execution & Practical Drill',
    subtitle: 'Penyelenggaraan Hybrid / On-Site',
    description: 'Pelaksanaan pelatihan interaktif, simulasi lapangan, observasi K3 langsung, serta pelaksanaan uji kompetensi resmi.',
  },
  {
    step: '06',
    title: 'Certification & Post-Audit',
    subtitle: 'Penerbitan Sertifikat & Evaluasi',
    description: 'Penerbitan Sertifikat Resmi Kemnaker RI / BNSP Garuda, penyerahan SKP Lisensi, serta laporan komprehensif bagi pimpinan perusahaan.',
  },
];

export const TRUST_INDUSTRIES = [
  { id: 'tambang', name: 'Pertambangan & Mineral (ESDM)', icon: 'Pickaxe' },
  { id: 'kesehatan', name: 'Kesehatan & Rumah Sakit (Kemenkes)', icon: 'Hospital' },
  { id: 'konstruksi', name: 'Konstruksi & Infrastruktur (PUPR)', icon: 'HardHat' },
  { id: 'manufaktur', name: 'Manufaktur & Pabrikasi Otomotif', icon: 'Factory' },
  { id: 'migas', name: 'Migas & Energi Terbarukan', icon: 'Flame' },
  { id: 'maritim', name: 'Pelabuhan, Logistik & IMDG Maritim', icon: 'Anchor' },
  { id: 'finansial', name: 'Perbankan & Fasilitas Gedung Tinggi', icon: 'Building' },
];

export const FEATURED_COURSE = COURSES[0];
